TOOLS = [
    {'slug': 'merge-pdf', 'title': 'Merge PDF', 'icon': 'merge-pdf.svg', 'desc': 'Combine multiple PDFs into one'},
    {'slug': 'split-pdf', 'title': 'Split PDF', 'icon': 'split-pdf.svg', 'desc': 'Split a PDF into multiple files'},
    {'slug': 'compress-pdf', 'title': 'Compress PDF', 'icon': 'compress-pdf.svg', 'desc': 'Reduce PDF file size'},
    {'slug': 'optimize-pdf', 'title': 'Optimize PDF', 'icon': 'optimize-pdf.svg', 'desc': 'Optimize PDF for web or print'},
    {'slug': 'rotate-pdf', 'title': 'Rotate PDF', 'icon': 'rotate-pdf.svg', 'desc': 'Rotate PDF pages'},
    {'slug': 'watermark-pdf', 'title': 'Watermark PDF', 'icon': 'watermark-pdf.svg', 'desc': 'Add watermark to your PDF'},
    {'slug': 'number-pdf', 'title': 'Number Pages', 'icon': 'number-pdf.svg', 'desc': 'Add page numbers to PDF'},
    {'slug': 'protect-pdf', 'title': 'Protect PDF', 'icon': 'protect-pdf.svg', 'desc': 'Protect PDF with password'},
    {'slug': 'unlock-pdf', 'title': 'Unlock PDF', 'icon': 'unlock-pdf.svg', 'desc': 'Remove PDF password'},
    {'slug': 'repair-pdf', 'title': 'Repair PDF', 'icon': 'repair-pdf.svg', 'desc': 'Fix damaged PDF file'},
    {'slug': 'organize-pdf', 'title': 'Organize PDF', 'icon': 'organize-pdf.svg', 'desc': 'Reorder, delete or sort pages'},
    {'slug': 'sign-pdf', 'title': 'Sign PDF', 'icon': 'sign-pdf.svg', 'desc': 'Electronically sign your PDF'},
    {'slug': 'annotate-pdf', 'title': 'Annotate PDF', 'icon': 'annotate-pdf.svg', 'desc': 'Add notes and highlights'},
    {'slug': 'redact-pdf', 'title': 'Redact PDF', 'icon': 'redact-pdf.svg', 'desc': 'Hide sensitive information'},
    {'slug': 'pdf-to-word', 'title': 'PDF to Word', 'icon': 'pdf-to-word.svg', 'desc': 'Convert PDF to DOCX'},
    {'slug': 'word-to-pdf', 'title': 'Word to PDF', 'icon': 'word-to-pdf.svg', 'desc': 'Convert DOCX to PDF'},
    {'slug': 'pdf-to-image', 'title': 'PDF to Image', 'icon': 'pdf-to-image.svg', 'desc': 'Convert PDF pages to images'},
    {'slug': 'image-to-pdf', 'title': 'Image to PDF', 'icon': 'image-to-pdf.svg', 'desc': 'Convert images to PDF'},
    {'slug': 'pdf-to-excel', 'title': 'PDF to Excel', 'icon': 'pdf-to-excel.svg', 'desc': 'Convert table data to Excel'},
    {'slug': 'excel-to-pdf', 'title': 'Excel to PDF', 'icon': 'excel-to-pdf.svg', 'desc': 'Convert XLSX to PDF'},
    {'slug': 'pdf-to-powerpoint', 'title': 'PDF to PowerPoint', 'icon': 'pdf-to-powerpoint.svg', 'desc': 'Convert PDF to PPTX'},
    {'slug': 'powerpoint-to-pdf', 'title': 'PowerPoint to PDF', 'icon': 'powerpoint-to-pdf.svg', 'desc': 'Convert PPTX to PDF'},
    {'slug': 'ocr-pdf', 'title': 'OCR PDF', 'icon': 'ocr-pdf.svg', 'desc': 'Extract text from scanned PDFs'},
    {'slug': 'extract-text', 'title': 'Extract Text', 'icon': 'extract-text.svg', 'desc': 'Extract text from PDF'},
    {'slug': 'extract-images', 'title': 'Extract Images', 'icon': 'extract-images.svg', 'desc': 'Extract images from PDF'},
    {'slug': 'deskew-pdf', 'title': 'Deskew PDF', 'icon': 'deskew-pdf.svg', 'desc': 'Straighten pages automatically'},
    {'slug': 'crop-pdf', 'title': 'Crop PDF', 'icon': 'crop-pdf.svg', 'desc': 'Crop PDF pages'},
    {'slug': 'resize-pdf', 'title': 'Resize PDF', 'icon': 'resize-pdf.svg', 'desc': 'Resize PDF page size'},
    {'slug': 'flatten-pdf', 'title': 'Flatten PDF', 'icon': 'flatten-pdf.svg', 'desc': 'Flatten annotations & layers'},
    {'slug': 'metadata-editor', 'title': 'Metadata Editor', 'icon': 'metadata-editor.svg', 'desc': 'Edit PDF info/metadata'},
    {'slug': 'fill-forms', 'title': 'Fill PDF Forms', 'icon': 'fill-forms.svg', 'desc': 'Fill form fields in PDF'},
    {'slug': 'background-remover', 'title': 'Remove Background', 'icon': 'background-remover.svg', 'desc': 'Remove image background'},
]

AI_TOOLS = [
    {"slug": "ai-editor", "title": "AI PDF Editor", "icon": "ai-editor.svg", "desc": "Edit PDF using AI", "url": "/ai/editor"},
    {"slug": "ai-summarizer", "title": "AI Summarizer", "icon": "ai-summarizer.svg", "desc": "Summarize documents with AI", "url": "/ai/summarizer"},
    {"slug": "ai-chat", "title": "Chat with PDF", "icon": "ai-chat.svg", "desc": "Chat with your document", "url": "/ai/chat"},
    {"slug": "ai-translate", "title": "AI Translator", "icon": "ai-translate.svg", "desc": "Translate PDF text", "url": "/ai/translate"},
    {"slug": "ai-table-extract", "title": "AI Table Extractor", "icon": "ai-table.svg", "desc": "Extract tables using AI", "url": "/ai/table"},
]

SLUG_TO_TOOL = {t["slug"]: t for t in TOOLS}
SLUG_TO_AI_TOOL = {t["slug"]: t for t in AI_TOOLS}
